spring:
  application:
    name: "Ngelmak Authentication Service"
  datasource:
    url: jdbc:postgresql://localhost:5432/ngelmak_auth_db
    username: ngelmak
    password: ngelmak
  liquibase:
    change-log: classpath:config/liquibase/master.xml
    enabled: false
